apiVersion: v1
kind: Service
metadata:
  name: microservice-payment-svc
spec:
  selector:
    app: microservice-payment
  ports:
    - protocol: TCP
      port: 90
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-order
  labels:
    app: microservice-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-order
  template:
    metadata:
      labels:
        app: microservice-order
    spec:
      containers:
      - name: microservice-order
        image: payment-microsvc:1.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      serviceAccountName: default