version: '3.9'
services:
  order:
    container_name: order
    build:
      context: ./backend-order-mgmt-system
      target: development
    volumes:
      - ./backend-order-mgmt-system:/usr/src/app
      - /backend-order-mgmt-system/usr/src/app/node_modules
      # - ./:/order
      # - /usr/src/app/node_modules
    ports:
      - 7000:7000
    command: npm run start:dev
    # env_file:
    #   - ./backend-order-mgmt-system/.env
    networks:
      - webnet
    links:
      - mongodb
      - payment
    depends_on:
      - mongodb
    environment:
      MONGO_USER: app_user
      MONGO_PASSWORD: app_password
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
  payment:
    container_name: payment
    build: ./microservice-payment
    ports: 
      - 8080:8080
    networks:
      - webnet
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
