order:
  name: order-micro-svc
  replicas: 1

  image:
    name: order-micro-svc
    tag: v1.0
    port: 7000
  
  service:
    name: order-micro-svc
    type: LoadBalancer


paymentservice:
  name: payment
  replicas: 1

  image:
    name: payment-micro-svc
    tag: v1.0
    port: 8080
  
  service:
    name: payment

mongodb:
  name: mongodb

  image:
    port: 27017

  service:
    name: mongodb
