apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  selector:
    app: {{ .Values.mongodb.service.name }}
  ports:
    - port: 27017
      targetPort: {{ .Values.mongodb.image.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: mongo
          ports:
            - containerPort: {{ .Values.mongodb.image.port }}
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: app_user
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: app_password
          - name: MONGO_INITDB_DATABASE
            value: admin
          volumeMounts:
            - name: storage
              mountPath: /data/db
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc