version: '3.9'
services:
  order:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7000:7000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
